---

- name: Clean local checkout directory
  local_action: command rm -Rf /tmp/{{ servername }}/gitolite
 
- name: Locally checkout gitolite repo
  local_action: git 
  args:
    repo: "{{ git_addr }}/gitolite-admin.git"
    dest: /tmp/{{ servername }}/gitolite
    accept_hostkey: yes

- name: Fetch public keyfile
  fetch:
    flat: yes
    src: /home/auto/.ssh/id_rsa.pub
    dest: /tmp/{{ servername }}/gitolite/keydir/{{ servername }}.pub

- name: Add public keyfile to local repository
  local_action: command git add {{ servername }}.pub
  args:
    chdir: "/tmp/{{ servername }}/gitolite/keydir"

- name: Commit changes in local repository
  local_action: command git commit -m "{{ servername }} public key added by ansible"
  args:
    chdir: "/tmp/{{ servername }}/gitolite"

- name: Push changes in local repository
  local_action: command git push
  args:
    chdir: "/tmp/{{ servername }}/gitolite"

- name: Remove temporary/local gitolite checkout
  local_action: command rm -Rf /tmp/{{ servername }}/gitolite
