---
- name: "Install iptables system service file"
  notify: "systemd daemon-reload"
  template:
    src: "iptables.service.j2"
    dest: "/etc/systemd/system/iptables-forward.service"
    mode: "0644"
    owner: "root"
    group: "root"
  with_indexed_items: "{{ networkd_configures }}"

- name: Enable iptables-forward service
  systemd:
    name: iptables-forward
    enabled: yes

- name: Start iptables-forward service
  systemd:
    name: iptables-forward
    state: started
