---
servername: sn01
sn: 01

# cloud-init config
networkd_configures:
  - iface: eth0
    addresses:
      - 192.168.0.159/24
      #- fdca::1/64
    gateway4: 192.168.0.1
    dns_server:
      - 5.1.66.255
      - '2001:678:ed0:f000::'
      - 9.9.9.9

mesh_prefix: "2a03:2260:114"
radv_announce_default: true