---

- name: Generate radvd config
  notify: Restart radvd
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf

- name: Add systemd service file
  template:
    src: systemd.service
    dest: /etc/systemd/system/radvd.service
  register: radvd_servicefile

- name: Enable and start radvd
  service:
    name: radvd
    state: started
    enabled: yes
  when: radvd_servicefile.changed
