---

- hosts: "supernodes:{{ experimental_supernodes | default('') }}"
  pre_tasks:
    - name: "Import pre_tasks: reboot-required.yml"
      import_tasks: "include/reboot-required.yml"
      tags: [always]
    - name: "Import pre_task etckeeper"
      import_tasks: "include/etckeeper_pre.yml"
      tags: [always]
  roles:
    # General
    - { name: ff.influxdb, tags: influxdb, become: yes }
    - { name: ff.yanic, tags: yanic, become: yes }
    #- { name: ffh.grafana, tags: grafana, become: yes }
    - { name: ff.meshviewer, tags: meshviewer, become: yes }
    - { name: ff.wgbroker, tags: wgbroker, become: yes }
  post_tasks:
    - name: "Import post_task etckeeper"
      import_tasks: "include/etckeeper_post.yml"
      tags: [always]
